# Generated by Django 3.2.5 on 2022-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='0', max_length=32, unique=True)),
                ('temperature', models.CharField(default='0', max_length=32)),
                ('feelslike', models.CharField(default='0', max_length=32)),
                ('pressure', models.CharField(default='0', max_length=32)),
                ('humidity', models.CharField(default='0', max_length=32)),
                ('minTemperature', models.CharField(default='0', max_length=32)),
                ('maxTemperature', models.CharField(default='0', max_length=32)),
                ('wind_speed', models.CharField(default='0', max_length=32)),
                ('wind_deg', models.CharField(default='0', max_length=32)),
                ('clouds', models.CharField(default='0', max_length=32)),
                ('weather_id', models.CharField(default='0', max_length=32)),
                ('weather_main', models.CharField(default='None', max_length=32)),
                ('weather_description', models.CharField(default='None', max_length=32)),
                ('weather_icon', models.CharField(default='None', max_length=32)),
            ],
        ),
    ]
