# Generated by Django 4.0.5 on 2022-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('monday', models.IntegerField(blank=True, null=True)),
                ('tuesday', models.IntegerField(blank=True, null=True)),
                ('wednesday', models.IntegerField(blank=True, null=True)),
                ('thursday', models.IntegerField(blank=True, null=True)),
                ('friday', models.IntegerField(blank=True, null=True)),
                ('saturday', models.IntegerField(blank=True, null=True)),
                ('sunday', models.IntegerField(blank=True, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarDates',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('exception_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('agency_id', models.IntegerField(blank=True, null=True)),
                ('route_short_name', models.CharField(blank=True, max_length=6, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=40, null=True)),
                ('route_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(blank=True, max_length=20, null=True)),
                ('shape_pt_lat', models.FloatField(blank=True, null=True)),
                ('shape_pt_lon', models.FloatField(blank=True, null=True)),
                ('shape_pt_sequence', models.IntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shapes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=40, null=True)),
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=40, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=40, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=40, null=True)),
                ('stop_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_headsign', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_type', models.IntegerField(blank=True, null=True)),
                ('drop_off_type', models.IntegerField(blank=True, null=True)),
                ('shape_dist_traveled', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stop_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop_id', models.CharField(blank=True, max_length=20, null=True)),
                ('to_stop_id', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_type', models.IntegerField(blank=True, null=True)),
                ('min_transfer_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, max_length=20, null=True)),
                ('service_id', models.CharField(blank=True, max_length=5, null=True)),
                ('trip_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=20, null=True)),
                ('trip_headsign', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
    ]
