# Generated by Django 4.0.5 on 2022-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('date', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('temperature', models.CharField(blank=True, max_length=32, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'daily_weather',
                'managed': False,
            },
        ),
    ]
