# Generated by Django 4.0.5 on 2022-06-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusesUpdates',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField(blank=True, null=True)),
                ('trip_id', models.TextField(blank=True, null=True)),
                ('route_id', models.TextField(blank=True, null=True)),
                ('start_time', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
                ('schedule_relationship', models.TextField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('stop_sequence', models.BigIntegerField(blank=True, null=True)),
                ('stop_id', models.TextField(blank=True, null=True)),
                ('arrival_delay', models.BigIntegerField(blank=True, null=True)),
                ('arrival_time', models.BigIntegerField(blank=True, null=True)),
                ('departure_delay', models.BigIntegerField(blank=True, null=True)),
                ('departure_time', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buses_updates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('date', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('temperature', models.CharField(blank=True, max_length=32, null=True)),
                ('weather_icon', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'daily_weather',
                'managed': False,
            },
        ),
    ]
