# Generated by Django 4.0.5 on 2022-06-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_busesupdates_dailyweather'),
        ('buses', '0002_dailyweather'),
    ]

    operations = [
    ]
