# Generated by Django 4.0.5 on 2022-07-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_merge_20220629_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('date', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(blank=True, max_length=32, null=True)),
                ('uvi', models.FloatField(blank=True, max_length=32, null=True)),
                ('humidity', models.FloatField(blank=True, max_length=32, null=True)),
                ('wind', models.FloatField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'hourly_weather',
                'managed': False,
            },
        ),
    ]
