# Generated by Django 4.0.5 on 2022-07-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_hourlyweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfers',
        ),
    ]
